services:
  - type: web
    name: ytconverter
    env: node
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg yt-dlp
      npm install
      cd frontend && npm install && npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 